
apiVersion: v1
kind: Service
metadata:
  name: auth-wfm
  annotations:
    cloud.google.com/neg: '{"ingress": false}' # Disable NEG

spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  selector:
    app: auth-wfm
  type: LoadBalancer

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: web-crm
# spec:
#   defaultBackend:
#     service:
#       name: web-crm
#       port:
#         number: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-wfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-wfm
  template:
    metadata:
      labels:
        app: auth-wfm
    spec:
      # nodeSelector:
      #   kubernetes.io/os: windows
      containers:
      - name: auth-wfm
        image: us.gcr.io/slz-namph-authoritycrm/wfmapi:v1
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 256Mi
